[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
core = { path = "../core" }
macros = { path = "../macros" }
scraper = { path = "../scraper" }
serde_json = "1"
tabled = "0.20.0"
tokio.workspace = true
thiserror.workspace = true
