[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
serde.workspace = true
sqlx.workspace = true
utoipa.workspace = true
utoipa-scalar.workspace = true
thiserror.workspace = true
scraper = { path = "../scraper" }
